# Generated by Django 6.0.7 on 2026-07-18

import decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(max_length=150, verbose_name="nombre del prestatario"),
                ),
                (
                    "borrower_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="teléfono del prestatario",
                    ),
                ),
                (
                    "borrower_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="correo del prestatario",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("0.01")
                            )
                        ],
                        verbose_name="monto",
                    ),
                ),
                ("loan_date", models.DateField(verbose_name="fecha del préstamo")),
                ("due_date", models.DateField(verbose_name="fecha de vencimiento")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pendiente"), ("paid", "Pagado")],
                        default="pending",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-loan_date", "-created_at"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="loans_loan_amount_positive",
                    )
                ],
            },
        ),
    ]
