# Generated by Django 6.0.7 on 2026-07-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefono del prestatario'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(verbose_name='fecha del prestamo'),
        ),
    ]
