# Generated by Django 6.0.7 on 2026-07-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_borrower_phone_alter_loan_loan_date'),
        ('loans', '0003_loan_currency'),
    ]

    operations = [
    ]
